### ISSUE TITLE
IndexKernel.cu:53 errors

### ISSUE THREAD

**Issue by alan101-tech** [cywang97/StreamingTransformer#11]
Hi,
   I am currently trying to run the librispeech demo. But, when i run ./train.sh, error happens:

/opt/conda/conda-bld/pytorch_1549636813070/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda [](int)->auto::operator()(int)->auto: block: [34,0,0], thread: [94,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1549636813070/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda [](int)->auto::operator()(int)->auto: block: [34,0,0], thread: [95,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1549636813070/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda [](int)->auto::operator()(int)->auto: block: [34,0,0], thread: [96,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1549636813070/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda [](int)->auto::operator()(int)->auto: block: [34,0,0], thread: [97,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1549636813070/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda [](int)->auto::operator()(int)->auto: block: [34,0,0], thread: [98,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1549636813070/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda [](int)->auto::operator()(int)->auto: block: [34,0,0], thread: [99,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.

Did you meet this error before?

Thank you very much!

**Comment by gothiswaysir** [comment]
@alan101-tech Hi, I encountered the same error, did you solve it?

**Comment by alan101-tech** [comment]
Yes, in file "conf/train_streaming_transformer.yaml",  change "transformer-input-layer" from "conv2d" to "custom", the error will be gone.

**Comment by gothiswaysir** [comment]
> Yes, in file "conf/train_streaming_transformer.yaml", change "transformer-input-layer" from "conv2d" to "custom", the error will be gone.

Thank you!
My case is different, there are some out-of-bounds data in the data_aligned.json

**Comment by alan101-tech** [comment]
solved
