### ISSUE TITLE
How can I get the the ''/path/to/model'' in Step 2. Viterbi decoding?

### ISSUE THREAD

**Issue by Gqwert123** [cywang97/StreamingTransformer#2]
Hi,
I am confused how can I get the the ''/path/to/model'' in Step 2. Viterbi decoding?
Step 2. Viterbi decoding
To train a TA based streaming Transformer, the alignments between CTC paths and transcriptions are required. In our work, we apply Viterbi decoding using the offline Transformer model.

cd egs/librispeech/asr1
./viterbi_decode.sh /path/to/model

Thanks a lot.

**Comment by cywang97** [comment]
Hi,
In my experiment, I simply use the offline model provided by ESPnet to perform viterbi decoding. (https://github.com/espnet/espnet/blob/master/egs/librispeech/asr1/RESULTS.md) You can also train an offline model by yourself using `e2e_asr_transformer.py` and set `streaming` argument to False.

**Comment by Gqwert123** [comment]
> Hi,
> In my experiment, I simply use the offline model provided by ESPnet to perform viterbi decoding. (https://github.com/espnet/espnet/blob/master/egs/librispeech/asr1/RESULTS.md) You can also train an offline model by yourself using `e2e_asr_transformer.py` and set `streaming` argument to False.

Thanks a lot!
