### ISSUE TITLE
dict download

### ISSUE THREAD

**Issue by qmpzzpmq** [cywang97/StreamingTransformer#6]
Could you upload the dict as well? especially for the .model file

**Comment by cywang97** [comment]
You can download the dict here [https://drive.google.com/file/d/1lxq0uNP9jFCVIgaP5zbg_pVRWQ2OCGKJ/view?usp=sharing]

**Comment by cywang97** [comment]
You can download the dict in the following link:
https://drive.google.com/file/d/1lxq0uNP9jFCVIgaP5zbg_pVRWQ2OCGKJ/view?usp=sharing
