### ISSUE TITLE
Joint CTC-triggered attention decoding algorithm code

### ISSUE THREAD

**Issue by yjiangling** [cywang97/StreamingTransformer#9]
Hi, did you finish the implement of Joint CTC-triggered attention decoding algorithm? 

I complete the Streaming Transformer model train and finished the train with TensorFlow, but when I tried to finish the Joint CTC-triggered attention decoding algorithm, I was stucked in the CTCPREFIX algorithm, is there any good ideal to complete it? 

Papers:
[1]. STREAMING AUTOMATIC SPEECH RECOGNITION WITH THE TRANSFORMER MODEL
[2]. Streaming End-to-End Speech Recognition with Joint CTC-Attention Based Models

**Comment by Gqwert123** [comment]
I also meet this problem. That means how can I use the trained model to inference the utt ?

**Comment by cywang97** [comment]
> Hi, did you finish the implement of Joint CTC-triggered attention decoding algorithm?
> 
> I complete the Streaming Transformer model train and finished the train with TensorFlow, but when I tried to finish the Joint CTC-triggered attention decoding algorithm, I was stucked in the CTCPREFIX algorithm, is there any good ideal to complete it?
> 
> Papers:
> [1]. STREAMING AUTOMATIC SPEECH RECOGNITION WITH THE TRANSFORMER MODEL
> [2]. Streaming End-to-End Speech Recognition with Joint CTC-Attention Based Models

The function ``prefix_recognize`` is joint CTC-triggered attention decoding algorithm. You can use decode.sh for decoding.
I didn't understand your question clearly. Do you implement streaming Transformer with Tensorflow? And what do you mean by ``stucked in the CTCPREFIX algorithm``?

**Comment by yjiangling** [comment]
> > Hi, did you finish the implement of Joint CTC-triggered attention decoding algorithm?
> > I complete the Streaming Transformer model train and finished the train with TensorFlow, but when I tried to finish the Joint CTC-triggered attention decoding algorithm, I was stucked in the CTCPREFIX algorithm, is there any good ideal to complete it?
> > Papers:
> > [1]. STREAMING AUTOMATIC SPEECH RECOGNITION WITH THE TRANSFORMER MODEL
> > [2]. Streaming End-to-End Speech Recognition with Joint CTC-Attention Based Models
> 
> The function `prefix_recognize` is joint CTC-triggered attention decoding algorithm. You can use decode.sh for decoding.
> I didn't understand your question clearly. Do you implement streaming Transformer with Tensorflow? And what do you mean by `stucked in the CTCPREFIX algorithm`?

Thanks a lot for your time. Yes, I implement Streaming Transformer with TensorFlow and I'm trying to implement the joint CTC-Triggered Attention algorithm with TensorFlow. But compared with PyTorch, It seems that it's more difficult to implement it whith TensorFlow.

**Comment by yjiangling** [comment]
> > Hi, did you finish the implement of Joint CTC-triggered attention decoding algorithm?
> > I complete the Streaming Transformer model train and finished the train with TensorFlow, but when I tried to finish the Joint CTC-triggered attention decoding algorithm, I was stucked in the CTCPREFIX algorithm, is there any good ideal to complete it?
> > Papers:
> > [1]. STREAMING AUTOMATIC SPEECH RECOGNITION WITH THE TRANSFORMER MODEL
> > [2]. Streaming End-to-End Speech Recognition with Joint CTC-Attention Based Models
> 
> The function `prefix_recognize` is joint CTC-triggered attention decoding algorithm. You can use decode.sh for decoding.
> I didn't understand your question clearly. Do you implement streaming Transformer with Tensorflow? And what do you mean by `stucked in the CTCPREFIX algorithm`?

Sorry, could you please tell me the location of the function **prefix_recognize** ? I really can not find it. Thanks a lot.

**Comment by cywang97** [comment]
> > > Hi, did you finish the implement of Joint CTC-triggered attention decoding algorithm?
> > > I complete the Streaming Transformer model train and finished the train with TensorFlow, but when I tried to finish the Joint CTC-triggered attention decoding algorithm, I was stucked in the CTCPREFIX algorithm, is there any good ideal to complete it?
> > > Papers:
> > > [1]. STREAMING AUTOMATIC SPEECH RECOGNITION WITH THE TRANSFORMER MODEL
> > > [2]. Streaming End-to-End Speech Recognition with Joint CTC-Attention Based Models
> > 
> > 
> > The function `prefix_recognize` is joint CTC-triggered attention decoding algorithm. You can use decode.sh for decoding.
> > I didn't understand your question clearly. Do you implement streaming Transformer with Tensorflow? And what do you mean by `stucked in the CTCPREFIX algorithm`?
> 
> Sorry, could you please tell me the location of the function **prefix_recognize** ? I really can not find it. Thanks a lot.

It's in https://github.com/cywang97/StreamingTransformer/blob/master/espnet/nets/pytorch_backend/streaming_transformer.py

**Comment by yjiangling** [comment]
> > > > Hi, did you finish the implement of Joint CTC-triggered attention decoding algorithm?
> > > > I complete the Streaming Transformer model train and finished the train with TensorFlow, but when I tried to finish the Joint CTC-triggered attention decoding algorithm, I was stucked in the CTCPREFIX algorithm, is there any good ideal to complete it?
> > > > Papers:
> > > > [1]. STREAMING AUTOMATIC SPEECH RECOGNITION WITH THE TRANSFORMER MODEL
> > > > [2]. Streaming End-to-End Speech Recognition with Joint CTC-Attention Based Models
> > > 
> > > 
> > > The function `prefix_recognize` is joint CTC-triggered attention decoding algorithm. You can use decode.sh for decoding.
> > > I didn't understand your question clearly. Do you implement streaming Transformer with Tensorflow? And what do you mean by `stucked in the CTCPREFIX algorithm`?
> > 
> > 
> > Sorry, could you please tell me the location of the function **prefix_recognize** ? I really can not find it. Thanks a lot.
> 
> It's in https://github.com/cywang97/StreamingTransformer/blob/master/espnet/nets/pytorch_backend/streaming_transformer.py

Ok，thank you very much for your help!
